language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t azegheru/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true azegheru/react-test npm test

after_success:
  - docker build -t azegheru/multi-client ./client
  - docker build -t azegheru/multi-nginx ./nginx
  - docker build -t azegheru/multi-server ./server
  - docker build -t azegheru/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push azegheru/multi-client
  - docker push azegheru/multi-nginx
  - docker push azegheru/multi-server
  - docker push azegheru/multi-worker

  
